//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : Bus.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//

namespace RentalCA
{
    public class Bus : Vehicle
    {
        private int Television;
        private int MaxPassengers;
    }
}
