//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : Car.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//

namespace RentalCA
{
    public class Car : Vehicle
    {
        private string CarType;
        private int MaxSeats;
    }
}
