//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : Customer.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//

namespace RentalCA
{
    public class Customer
    {
        private int customerID;
        private string customerName;
        private int telephone;
        private string emailAddress;

        public int CustomerID
        {
            get
            {
                return customerID;
            }

            set
            {
                customerID = value;
            }
        }

        public string CustomerName
        {
            get
            {
                return customerName;
            }

            set
            {
                customerName = value;
            }
        }

        public int Telephone
        {
            get
            {
                return telephone;
            }

            set
            {
                telephone = value;
            }
        }

        public string EmailAddress
        {
            get
            {
                return emailAddress;
            }

            set
            {
                emailAddress = value;
            }
        }
    }
}
