//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : EnquireStatusControl.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//
using System;
namespace RentalCA
{
    public class EnquireStatusControl
    {
        public EnquireStatusControl()
        {

        }
        public Vehicle RetrieveVehicle(string carPlateNumber)
        {

            VehicleDAO vehicleDAO = VehicleDAO.getInstance();

            try
            {
                vehicleDAO.openConnection();
                Vehicle v = vehicleDAO.RetrieveVehicleDetails(carPlateNumber);
                return v;
            }
            catch (Exception)
            {
                throw;           // preserve stack trace     
            }
            finally
            {
                vehicleDAO.CloseConnection();
            }
        }
    }
}
