//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : RentalTransactions.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//
using System;
namespace RentalCA
{
    public class RentalTransactions
    {
        private int transID;
        private DateTime rentalStartDate;
        private DateTime rentalTargetEndDate;
        private DateTime rentalActualEndDate;
        private int customerID;

        public int TransID
        {
            get
            {
                return transID;
            }

            set
            {
                transID = value;
            }
        }

        public DateTime RentalStartDate
        {
            get
            {
                return rentalStartDate;
            }

            set
            {
                rentalStartDate = value;
            }
        }

        public DateTime RentalTargetEndDate
        {
            get
            {
                return rentalTargetEndDate;
            }

            set
            {
                rentalTargetEndDate = value;
            }
        }

        public DateTime RentalActualEndDate
        {
            get
            {
                return rentalActualEndDate;
            }

            set
            {
                rentalActualEndDate = value;
            }
        }

        public int CustomerID
        {
            get
            {
                return customerID;
            }

            set
            {
                customerID = value;
            }
        }
    }
}
