//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : ReturnVehicleControl.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//
using System;
namespace RentalCA
{
    public class ReturnVehicleControl
    {
        public ReturnVehicleControl()
        {
        }

        public void CalculateAmount()
        {
        }
        
        
        public void ReturnTransaction(string carPlateNumber)
        {
            VehicleDAO dao = VehicleDAO.getInstance();
            try
            {
                int rentalRate;
                dao.openConnection();
                RentalTransactions t = dao.retrieveTransactionRecord(carPlateNumber, out rentalRate);
                CreateTransactionDetailsUI(t, rentalRate);
            }
            catch (Exception)
            {

                throw;
            }
            finally
            {
                dao.CloseConnection();
            }
    
        }

        public void CreateTransactionDetailsUI(RentalTransactions transaction, int rentalRate)
        {
            ReturnDetailsUI f = new ReturnDetailsUI();
            f.displayTransactionDetails(transaction, rentalRate);
            f.ShowDialog();

        }
    }
}
