//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : Truck.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//
using System;
namespace RentalCA
{
    public class Truck : Vehicle
    {
        private float MaxCargo;
        private int NumberWheels;
    }
}
