//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Rental
//  @ File Name : Vehicle.cs
//  @ Date : 6/10/2017
//  @ Author : 
//
//
using System;
namespace RentalCA
{

    public class Vehicle
    {


        private string _model;

        public string Model
        {
            get { return _model; }
            set { _model = value; }
        }
        private string _carPlateNumber;

        public string CarPlateNumber
        {
            get { return _carPlateNumber; }
            set { _carPlateNumber = value; }
        }
        private string _colour;

        public string Colour
        {
            get { return _colour; }
            set { _colour = value; }
        }
        private string _engineSerialNumber;

        public string EngineSerialNumber
        {
            get { return _engineSerialNumber; }
            set { _engineSerialNumber = value; }
        }
        private string _rentalStatus;

        public string RentalStatus
        {
            get { return _rentalStatus; }
            set { _rentalStatus = value; }
        }
        private double _rentalRate;

        public double RentalRate
        {
            get { return _rentalRate; }
            set { _rentalRate = value; }
        }



    }


}
